---
abstract: 'Perl extension for parsing TeX XDV files'
author:
  - 'Rick Myers <jrm@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TeX-XDV-Parse
no_index:
  directory:
    - t
    - inc
requires:
  TeX::DVI::Parse: 0
version: 0.01
